=== UO301831/SEW/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/circuito" elementFormDefault="qualified" targetNamespace="http://tempuri.org/circuito" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad_proxima" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador_principal" />
				<xs:element ref="bibliografia" />
				<xs:element ref="fotografia" />
				<xs:element ref="multimedia" />
				<xs:element ref="origen" />
				<xs:element ref="puntos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="medida" type="xs:positiveInteger" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="medida" type="xs:positiveInteger" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:date">
					<xs:attribute name="fechaISO" type="xs:date" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="hora" type="xs:date" />
	<xs:element name="vueltas" type="xs:positiveInteger" />
	<xs:element name="localidad_proxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador_principal" type="xs:string" />
	<xs:element name="bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="enlace" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="imagen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagen">
		<xs:complexType>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="src" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="multimedia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="src" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="origen">
		<xs:complexType>
			<xs:attribute name="nombre" type="xs:string" />
			<xs:attribute name="longitud" type="xs:string" use="required" />
			<xs:attribute name="latitud" type="xs:string" use="required" />
			<xs:attribute name="altitud" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fin" />
			</xs:sequence>
			<xs:attribute name="distancia" type="xs:positiveInteger" use="required" />
			<xs:attribute name="unidad" type="xs:positiveInteger" />
			<xs:attribute name="sector" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- TODO CUIDADO CON LAS UNIDADES DE LONGITUD LATITUD Y ALTITUD-->
	<xs:element name="fin">
		<xs:complexType>
			<xs:attribute name="longitud" type="xs:string" use="required" />
			<xs:attribute name="latitud" type="xs:string" use="required" />
			<xs:attribute name="altitud" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tiempo" type="xs:duration" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto">
		<xs:complexType>
			<xs:attribute name="puesto" type="xs:positiveInteger" use="required" />
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="puntos" type="xs:nonNegativeInteger" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO301831/SEW/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xsi:noNamespaceSchemaLocation="circuito.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <nombre>Red Bull Ring - Spielberg</nombre>
  <longitud medida="m">4300</longitud>
  <anchura medida="m">12</anchura>
  <fecha fechaISO="2025-08-17">Domingo 17 de agosto de 2025</fecha>
  <hora>14:00h</hora>
  <vueltas>28</vueltas>
  <localidad_proxima>Zeltweg</localidad_proxima>
  <pais>Austria</pais>
  <patrocinador_principal>Bwin</patrocinador_principal>

  <bibliografia>
    <referencia nombre="The Official Home of MotoGP" enlace="https://www.motogp.com/es/calendar/2025/event/austria/2691a49e-a593-4119-8fe4-826017d5f2dd?tab=overview"/>
    <referencia nombre="Motorbike Magazine" enlace="https://www.motorbikemag.es/horario-motogp-gp-austria-red-bull-ring-fecha-hora-carreras/"/>
    <referencia nombre="DAZN" enlace="https://www.dazn.com/es-ES/news/motor/circuito-red-bull-ring-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-austria-mundial-f1-motogp/11mzmm2gb230a1fcbe6anph2tc"/>
  </bibliografia>

  <fotografia>
    <imagen nombre="recta" src="multimedia/recta.jpg"/>
    <imagen nombre="curva" src="multimedia/curva.jpg"/>
  </fotografia>

  <multimedia>
    <video nombre="Circuito" src="multimedia/circuito.mp4"/>
  </multimedia>

  <origen nombre="Punto de origen de la pista" longitud="14°45'54E" latitud="47°13'12N" altitud="677"/>

  <puntos>
    <tramo distancia="800" unidad="m" sector="1">
      <fin longitud="14°45'58E" latitud="47°13'15N" altitud="678"/>
    </tramo>
    <tramo distancia="700" unidad="m" sector="2">
      <fin longitud="14°45'56E" latitud="47°13'20N" altitud="679"/>
    </tramo>
    <tramo distancia="600" unidad="m" sector="3">
      <fin longitud="14°45'51E" latitud="47°13'18N" altitud="676"/>
    </tramo>
    <tramo distancia="700" unidad="m" sector="4">
      <fin longitud="14°45'48E" latitud="47°13'14N" altitud="675"/>
    </tramo>
    <tramo distancia="600" unidad="m" sector="5">
      <fin longitud="14°45'50E" latitud="47°13'10N" altitud="676"/>
    </tramo>
    <tramo distancia="900" unidad="m" sector="6">
      <fin longitud="14°45'54E" latitud="47°13'12N" altitud="677"/>
    </tramo>
  </puntos>

  <vencedor nombre="Marc Márquez" tiempo="42:11.006"/>

  <clasificacion>
    <piloto puesto="1" nombre="Marc Márquez" puntos="545"/>
    <piloto puesto="2" nombre="Álex Márquez" puntos="362"/>
    <piloto puesto="3" nombre="Francesco Bagnaia" puntos="274"/>
  </clasificacion>
</circuito>
